name: Deploy React App

on:
  workflow_dispatch: {}
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      artifact_url: ${{ steps.generate_artifact.outputs.artifact_url }}
    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 📦 Instalar dependencias
        run: npm install

      - name: ⚙️ Construir la aplicación
        run: npm run build
        
      - name: 🔍 Verificar si la carpeta build existe
        run: ls -la

      - name: 🗜️ Comprimir el build
        run: |
          zip -r build.zip dist

      - name: Validate build.zip
        run: |
          echo "Listing contents of Export directory:"
          ls -la Export
          echo "Checking build.zip:"
          ls -la build.zip || echo "build.zip not found!"

      - name: 📤 Guardar el ZIP como artefacto
        uses: actions/upload-artifact@v4
        id: upload_artifact
        with:
          name: react-build
          path: build.zip

      - name: Generate Artifact URL
        id: generate_artifact
        run: |
          echo "::set-output name=artifact_url::https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload_artifact.outputs.artifact-id }}/zip"

  deploy:
    runs-on: ubuntu-latest
    needs: export-and-deploy
    steps:
      - name: 📥 Descargar el artefacto
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: .

      - name: 🚀 Subir al servidor por SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "build.zip"
          target: "/home/${{ secrets.SSH_USER }}"

      - name: 🔧 Conectar por SSH y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            APP_DIR="${HOME}/${{ secrets.APP_DIR }}"
            ARTIFACT_URL="${{ needs.export-and-deploy.outputs.artifact_url }}"
            TEMP_ZIP="$APP_DIR/Export.zip"

            # Limpiar el directorio si existe
            if [ -d "$APP_DIR" ]; then
              echo "Cleaning APP_DIR..."
              rm -rf "${APP_DIR:?}/*"
            else
              echo "Creating APP_DIR..."
              mkdir -p "$APP_DIR"
            fi

            # Descargar el archivo ZIP
            echo "Downloading artifact..."
            curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "$ARTIFACT_URL" -o "$TEMP_ZIP"

            # Verificar el contenido del ZIP descargado
            echo "Checking ZIP contents..."
            unzip -l "$TEMP_ZIP"

            # Comprobar si la descarga fue exitosa
            if [ $? -ne 0 ]; then
              echo "Failed to download artifact."
              exit 1
            fi

            # Descomprimir el archivo en APP_DIR
            echo "Extracting ZIP..."
            unzip -o "$TEMP_ZIP" -d "$APP_DIR"

            # Eliminar el ZIP para evitar conflictos futuros
            echo "Deleting ZIP..."
            rm -f "$TEMP_ZIP"

            echo "Deployment finished!"
